### ISSUE TITLE
Using code_builder for generating source code?

### ISSUE THREAD

**Issue by kostadin-damyanov-prime** [timfreiheit/R.Flutter#35]
Hello.

I am working on adding a new feature to this package but while reading the code I saw that it uses just string buffers to generate the source code. It looks like this approach is quite fast.

I am wondering if there is any value in updating the generator to use something like [code_builder](https://pub.dev/packages/code_builder). I can update it and open a PR if I know that this is something that is needed. Otherwise the current approach works just fine and does not cause any troubles AFAIK.

@timfreiheit what are your thoughts on this?

**Comment by timfreiheit** [comment]
Hey,
Using code_builder would definitely be an option. 
When starting initially this library missed some features which made it impossible for my usecase.
Unfortunately I do not remember what those limitations where.
What feature are you trying to implement?

**Comment by kostadin-damyanov-prime** [comment]
I am trying to make it possible to split translations by feature so they are not stored in a single arb file.
This will make big projects a bit more organised and also reduce merge conflicts when people are adding new features to a project at the same time.

My plan is to have it like this:

```yaml
r_flutter:
  intl: lib/i18n/arb/en.arb
  intl_features:
    - name: home
      path: lib/i18n/arb/homezz/
    - name: announcements
    - name: profile
```

The `intl_features` element will be optional so we will have backwards compatibility.
Every intl feature is a name and path pair. The path will be optional and if is not provided it will be assumed to be a subfolder of the base translation directory.
So for example the path value for the profile feature will be assumed to be `lib/i18n/arb/profile/` and it will contain its own `en.arb`, `de.arb`, `bg.arb` etc. files.

And then the `I18n` class will need to provide them as instance properties like this `I18n.of(context).profile.appBarTitle`.
This means we will have to generate `I18nHome`, `I18nProfile` classes and also the same for the keys and lookup classes I think.

Feedback is welcome.

**Comment by timfreiheit** [comment]
This sounds like a very useful feature
